export interface ThemePreset {
  name: string;
  label: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    sidebar: string;
  };
  light: Record<string, string>;
  dark: Record<string, string>;
}

export const themePresets: ThemePreset[] = [
  {
    name: "oceanic",
    label: "Oceanic Corporate",
    colors: { primary: "#2563EB", secondary: "#64748B", accent: "#F59E0B", background: "#F8FAFC", sidebar: "#0F172A" },
    light: {
      "--background": "#F8FAFC",
      "--foreground": "#0F172A",
      "--card": "#FFFFFF",
      "--card-foreground": "#0F172A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#0F172A",
      "--primary": "#2563EB",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#64748B",
      "--secondary-foreground": "#FFFFFF",
      "--muted": "#F1F5F9",
      "--muted-foreground": "#64748B",
      "--accent": "#F59E0B",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#EF4444",
      "--destructive-foreground": "#FFFFFF",
      "--success": "#22C55E",
      "--success-foreground": "#FFFFFF",
      "--warning": "#F59E0B",
      "--warning-foreground": "#FFFFFF",
      "--info": "#3B82F6",
      "--info-foreground": "#FFFFFF",
      "--border": "#E2E8F0",
      "--input": "#E2E8F0",
      "--ring": "#2563EB",
      "--sidebar": "#0F172A",
      "--sidebar-foreground": "#F8FAFC",
      "--sidebar-accent": "#1E293B",
      "--sidebar-accent-foreground": "#F8FAFC",
      "--sidebar-border": "#1E293B",
    },
    dark: {
      "--background": "#0F172A",
      "--foreground": "#F8FAFC",
      "--card": "#1E293B",
      "--card-foreground": "#F8FAFC",
      "--popover": "#1E293B",
      "--popover-foreground": "#F8FAFC",
      "--primary": "#60A5FA",
      "--primary-foreground": "#0F172A",
      "--secondary": "#475569",
      "--secondary-foreground": "#F8FAFC",
      "--muted": "#1E293B",
      "--muted-foreground": "#94A3B8",
      "--accent": "#FBBF24",
      "--accent-foreground": "#0F172A",
      "--destructive": "#F87171",
      "--destructive-foreground": "#0F172A",
      "--success": "#4ADE80",
      "--success-foreground": "#0F172A",
      "--warning": "#FBBF24",
      "--warning-foreground": "#0F172A",
      "--info": "#60A5FA",
      "--info-foreground": "#0F172A",
      "--border": "#334155",
      "--input": "#334155",
      "--ring": "#60A5FA",
      "--sidebar": "#0A0F1A",
      "--sidebar-foreground": "#CBD5E1",
      "--sidebar-accent": "#1E293B",
      "--sidebar-accent-foreground": "#F8FAFC",
      "--sidebar-border": "#334155",
    },
  },
  {
    name: "indigo",
    label: "Tech Indigo",
    colors: { primary: "#6366F1", secondary: "#94A3B8", accent: "#EC4899", background: "#F1F5F9", sidebar: "#1E1B4B" },
    light: {
      "--background": "#F1F5F9",
      "--foreground": "#0F172A",
      "--card": "#FFFFFF",
      "--card-foreground": "#0F172A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#0F172A",
      "--primary": "#6366F1",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#94A3B8",
      "--secondary-foreground": "#FFFFFF",
      "--muted": "#E2E8F0",
      "--muted-foreground": "#64748B",
      "--accent": "#EC4899",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#EF4444",
      "--destructive-foreground": "#FFFFFF",
      "--success": "#22C55E",
      "--success-foreground": "#FFFFFF",
      "--warning": "#F59E0B",
      "--warning-foreground": "#FFFFFF",
      "--info": "#6366F1",
      "--info-foreground": "#FFFFFF",
      "--border": "#E2E8F0",
      "--input": "#E2E8F0",
      "--ring": "#6366F1",
      "--sidebar": "#1E1B4B",
      "--sidebar-foreground": "#E0E7FF",
      "--sidebar-accent": "#312E81",
      "--sidebar-accent-foreground": "#E0E7FF",
      "--sidebar-border": "#312E81",
    },
    dark: {
      "--background": "#0F0A2E",
      "--foreground": "#E0E7FF",
      "--card": "#1E1B4B",
      "--card-foreground": "#E0E7FF",
      "--popover": "#1E1B4B",
      "--popover-foreground": "#E0E7FF",
      "--primary": "#818CF8",
      "--primary-foreground": "#0F0A2E",
      "--secondary": "#64748B",
      "--secondary-foreground": "#E0E7FF",
      "--muted": "#2A2560",
      "--muted-foreground": "#94A3B8",
      "--accent": "#F472B6",
      "--accent-foreground": "#0F0A2E",
      "--destructive": "#F87171",
      "--destructive-foreground": "#0F0A2E",
      "--success": "#4ADE80",
      "--success-foreground": "#0F0A2E",
      "--warning": "#FBBF24",
      "--warning-foreground": "#0F0A2E",
      "--info": "#818CF8",
      "--info-foreground": "#0F0A2E",
      "--border": "#312E81",
      "--input": "#312E81",
      "--ring": "#818CF8",
      "--sidebar": "#0A0820",
      "--sidebar-foreground": "#C7D2FE",
      "--sidebar-accent": "#312E81",
      "--sidebar-accent-foreground": "#E0E7FF",
      "--sidebar-border": "#312E81",
    },
  },
  {
    name: "emerald",
    label: "Emerald Eco",
    colors: { primary: "#059669", secondary: "#6B7280", accent: "#8B5CF6", background: "#F9FAFB", sidebar: "#064E3B" },
    light: {
      "--background": "#F9FAFB",
      "--foreground": "#111827",
      "--card": "#FFFFFF",
      "--card-foreground": "#111827",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#111827",
      "--primary": "#059669",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#6B7280",
      "--secondary-foreground": "#FFFFFF",
      "--muted": "#F3F4F6",
      "--muted-foreground": "#6B7280",
      "--accent": "#8B5CF6",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#EF4444",
      "--destructive-foreground": "#FFFFFF",
      "--success": "#10B981",
      "--success-foreground": "#FFFFFF",
      "--warning": "#F59E0B",
      "--warning-foreground": "#FFFFFF",
      "--info": "#3B82F6",
      "--info-foreground": "#FFFFFF",
      "--border": "#E5E7EB",
      "--input": "#E5E7EB",
      "--ring": "#059669",
      "--sidebar": "#064E3B",
      "--sidebar-foreground": "#D1FAE5",
      "--sidebar-accent": "#047857",
      "--sidebar-accent-foreground": "#D1FAE5",
      "--sidebar-border": "#047857",
    },
    dark: {
      "--background": "#022C22",
      "--foreground": "#D1FAE5",
      "--card": "#064E3B",
      "--card-foreground": "#D1FAE5",
      "--popover": "#064E3B",
      "--popover-foreground": "#D1FAE5",
      "--primary": "#34D399",
      "--primary-foreground": "#022C22",
      "--secondary": "#4B5563",
      "--secondary-foreground": "#D1FAE5",
      "--muted": "#065F46",
      "--muted-foreground": "#6EE7B7",
      "--accent": "#A78BFA",
      "--accent-foreground": "#022C22",
      "--destructive": "#F87171",
      "--destructive-foreground": "#022C22",
      "--success": "#34D399",
      "--success-foreground": "#022C22",
      "--warning": "#FBBF24",
      "--warning-foreground": "#022C22",
      "--info": "#60A5FA",
      "--info-foreground": "#022C22",
      "--border": "#065F46",
      "--input": "#065F46",
      "--ring": "#34D399",
      "--sidebar": "#022118",
      "--sidebar-foreground": "#A7F3D0",
      "--sidebar-accent": "#065F46",
      "--sidebar-accent-foreground": "#D1FAE5",
      "--sidebar-border": "#065F46",
    },
  },
  {
    name: "slate",
    label: "Slate Minimalist",
    colors: { primary: "#0F172A", secondary: "#475569", accent: "#10B981", background: "#F1F5F9", sidebar: "#0F172A" },
    light: {
      "--background": "#F1F5F9",
      "--foreground": "#0F172A",
      "--card": "#FFFFFF",
      "--card-foreground": "#0F172A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#0F172A",
      "--primary": "#0F172A",
      "--primary-foreground": "#F8FAFC",
      "--secondary": "#475569",
      "--secondary-foreground": "#FFFFFF",
      "--muted": "#E2E8F0",
      "--muted-foreground": "#64748B",
      "--accent": "#10B981",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#EF4444",
      "--destructive-foreground": "#FFFFFF",
      "--success": "#10B981",
      "--success-foreground": "#FFFFFF",
      "--warning": "#F59E0B",
      "--warning-foreground": "#FFFFFF",
      "--info": "#3B82F6",
      "--info-foreground": "#FFFFFF",
      "--border": "#E2E8F0",
      "--input": "#E2E8F0",
      "--ring": "#0F172A",
      "--sidebar": "#0F172A",
      "--sidebar-foreground": "#CBD5E1",
      "--sidebar-accent": "#1E293B",
      "--sidebar-accent-foreground": "#F8FAFC",
      "--sidebar-border": "#1E293B",
    },
    dark: {
      "--background": "#0A0F1A",
      "--foreground": "#E2E8F0",
      "--card": "#1E293B",
      "--card-foreground": "#E2E8F0",
      "--popover": "#1E293B",
      "--popover-foreground": "#E2E8F0",
      "--primary": "#E2E8F0",
      "--primary-foreground": "#0A0F1A",
      "--secondary": "#334155",
      "--secondary-foreground": "#E2E8F0",
      "--muted": "#1E293B",
      "--muted-foreground": "#94A3B8",
      "--accent": "#34D399",
      "--accent-foreground": "#0A0F1A",
      "--destructive": "#F87171",
      "--destructive-foreground": "#0A0F1A",
      "--success": "#34D399",
      "--success-foreground": "#0A0F1A",
      "--warning": "#FBBF24",
      "--warning-foreground": "#0A0F1A",
      "--info": "#60A5FA",
      "--info-foreground": "#0A0F1A",
      "--border": "#334155",
      "--input": "#334155",
      "--ring": "#E2E8F0",
      "--sidebar": "#060A12",
      "--sidebar-foreground": "#94A3B8",
      "--sidebar-accent": "#1E293B",
      "--sidebar-accent-foreground": "#E2E8F0",
      "--sidebar-border": "#334155",
    },
  },
  {
    name: "bordeaux",
    label: "Bordeaux Executive",
    colors: { primary: "#991B1B", secondary: "#525252", accent: "#D97706", background: "#FAFAFA", sidebar: "#450A0A" },
    light: {
      "--background": "#FAFAFA",
      "--foreground": "#1A1A1A",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A1A1A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A1A1A",
      "--primary": "#991B1B",
      "--primary-foreground": "#FAFAFA",
      "--secondary": "#525252",
      "--secondary-foreground": "#FAFAFA",
      "--muted": "#F5F5F5",
      "--muted-foreground": "#737373",
      "--accent": "#D97706",
      "--accent-foreground": "#FAFAFA",
      "--destructive": "#DC2626",
      "--destructive-foreground": "#FAFAFA",
      "--success": "#16A34A",
      "--success-foreground": "#FAFAFA",
      "--warning": "#D97706",
      "--warning-foreground": "#FAFAFA",
      "--info": "#2563EB",
      "--info-foreground": "#FAFAFA",
      "--border": "#E5E5E5",
      "--input": "#E5E5E5",
      "--ring": "#991B1B",
      "--sidebar": "#450A0A",
      "--sidebar-foreground": "#FECACA",
      "--sidebar-accent": "#7F1D1D",
      "--sidebar-accent-foreground": "#FECACA",
      "--sidebar-border": "#7F1D1D",
    },
    dark: {
      "--background": "#1A0A0A",
      "--foreground": "#FECACA",
      "--card": "#2D1515",
      "--card-foreground": "#FECACA",
      "--popover": "#2D1515",
      "--popover-foreground": "#FECACA",
      "--primary": "#DC2626",
      "--primary-foreground": "#FAFAFA",
      "--secondary": "#404040",
      "--secondary-foreground": "#FECACA",
      "--muted": "#2D1515",
      "--muted-foreground": "#A3A3A3",
      "--accent": "#F59E0B",
      "--accent-foreground": "#1A0A0A",
      "--destructive": "#EF4444",
      "--destructive-foreground": "#FAFAFA",
      "--success": "#22C55E",
      "--success-foreground": "#1A0A0A",
      "--warning": "#F59E0B",
      "--warning-foreground": "#1A0A0A",
      "--info": "#60A5FA",
      "--info-foreground": "#1A0A0A",
      "--border": "#450A0A",
      "--input": "#450A0A",
      "--ring": "#DC2626",
      "--sidebar": "#0F0505",
      "--sidebar-foreground": "#FCA5A5",
      "--sidebar-accent": "#7F1D1D",
      "--sidebar-accent-foreground": "#FECACA",
      "--sidebar-border": "#450A0A",
    },
  },
  {
    name: "ruby",
    label: "Ruby Vermelho",
    colors: { primary: "#D62828", secondary: "#C0C0C0", accent: "#9D0208", background: "#FFFFFF", sidebar: "#1A1A1A" },
    light: {
      "--background": "#FFFFFF",
      "--foreground": "#1A1A1A",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A1A1A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A1A1A",
      "--primary": "#D62828",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#C0C0C0",
      "--secondary-foreground": "#1A1A1A",
      "--muted": "#F5F5F5",
      "--muted-foreground": "#737373",
      "--accent": "#9D0208",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#DC2626",
      "--destructive-foreground": "#FFFFFF",
      "--success": "#16A34A",
      "--success-foreground": "#FFFFFF",
      "--warning": "#F59E0B",
      "--warning-foreground": "#1A1A1A",
      "--info": "#3B82F6",
      "--info-foreground": "#FFFFFF",
      "--border": "#E5E5E5",
      "--input": "#E5E5E5",
      "--ring": "#D62828",
      "--sidebar": "#1A1A1A",
      "--sidebar-foreground": "#E5E5E5",
      "--sidebar-accent": "#333333",
      "--sidebar-accent-foreground": "#FFFFFF",
      "--sidebar-border": "#333333",
    },
    dark: {
      "--background": "#1A0D0D",
      "--foreground": "#F5F5F5",
      "--card": "#2D1515",
      "--card-foreground": "#F5F5F5",
      "--popover": "#2D1515",
      "--popover-foreground": "#F5F5F5",
      "--primary": "#EF4444",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#A0A0A0",
      "--secondary-foreground": "#1A0D0D",
      "--muted": "#2D1515",
      "--muted-foreground": "#A3A3A3",
      "--accent": "#BA0208",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#F87171",
      "--destructive-foreground": "#1A0D0D",
      "--success": "#4ADE80",
      "--success-foreground": "#1A0D0D",
      "--warning": "#FBBF24",
      "--warning-foreground": "#1A0D0D",
      "--info": "#60A5FA",
      "--info-foreground": "#1A0D0D",
      "--border": "#404040",
      "--input": "#404040",
      "--ring": "#EF4444",
      "--sidebar": "#0F0808",
      "--sidebar-foreground": "#D4D4D4",
      "--sidebar-accent": "#333333",
      "--sidebar-accent-foreground": "#FFFFFF",
      "--sidebar-border": "#404040",
    },
  },
];
