/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResponsavelRouteImport } from './routes/responsavel'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InadimplentesRouteImport } from './routes/inadimplentes'
import { Route as GestaoOuvidoriaRouteImport } from './routes/gestao-ouvidoria'
import { Route as GestaoNoticiasRouteImport } from './routes/gestao-noticias'
import { Route as GestaoCategoriasRouteImport } from './routes/gestao-categorias'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as ResponsavelIndexRouteImport } from './routes/responsavel.index'
import { Route as AlunosIndexRouteImport } from './routes/alunos.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as ResponsavelDashboardRouteImport } from './routes/responsavel.dashboard'
import { Route as AssociadoPainelRouteImport } from './routes/associado.painel'
import { Route as AlunosNovoRouteImport } from './routes/alunos.novo'
import { Route as AlunosIdRouteImport } from './routes/alunos.$id'
import { Route as SiteTransparenciaRouteImport } from './routes/_site.transparencia'
import { Route as SiteOuvidoriaRouteImport } from './routes/_site.ouvidoria'
import { Route as SiteNoticiasRouteImport } from './routes/_site.noticias'
import { Route as SiteInstitucionalRouteImport } from './routes/_site.institucional'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as SiteAssociadoRouteImport } from './routes/_site.associado'

const ResponsavelRoute = ResponsavelRouteImport.update({
  id: '/responsavel',
  path: '/responsavel',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InadimplentesRoute = InadimplentesRouteImport.update({
  id: '/inadimplentes',
  path: '/inadimplentes',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoOuvidoriaRoute = GestaoOuvidoriaRouteImport.update({
  id: '/gestao-ouvidoria',
  path: '/gestao-ouvidoria',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoNoticiasRoute = GestaoNoticiasRouteImport.update({
  id: '/gestao-noticias',
  path: '/gestao-noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoCategoriasRoute = GestaoCategoriasRouteImport.update({
  id: '/gestao-categorias',
  path: '/gestao-categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsavelIndexRoute = ResponsavelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResponsavelRoute,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunosRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const ResponsavelDashboardRoute = ResponsavelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ResponsavelRoute,
} as any)
const AssociadoPainelRoute = AssociadoPainelRouteImport.update({
  id: '/associado/painel',
  path: '/associado/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosNovoRoute = AlunosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AlunosRoute,
} as any)
const AlunosIdRoute = AlunosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlunosRoute,
} as any)
const SiteTransparenciaRoute = SiteTransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOuvidoriaRoute = SiteOuvidoriaRouteImport.update({
  id: '/ouvidoria',
  path: '/ouvidoria',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNoticiasRoute = SiteNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInstitucionalRoute = SiteInstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAssociadoRoute = SiteAssociadoRouteImport.update({
  id: '/associado',
  path: '/associado',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao-categorias': typeof GestaoCategoriasRoute
  '/gestao-noticias': typeof GestaoNoticiasRoute
  '/gestao-ouvidoria': typeof GestaoOuvidoriaRoute
  '/inadimplentes': typeof InadimplentesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/responsavel': typeof ResponsavelRouteWithChildren
  '/associado': typeof SiteAssociadoRoute
  '/contato': typeof SiteContatoRoute
  '/institucional': typeof SiteInstitucionalRoute
  '/noticias': typeof SiteNoticiasRoute
  '/ouvidoria': typeof SiteOuvidoriaRoute
  '/transparencia': typeof SiteTransparenciaRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/associado/painel': typeof AssociadoPainelRoute
  '/responsavel/dashboard': typeof ResponsavelDashboardRoute
  '/alunos/': typeof AlunosIndexRoute
  '/responsavel/': typeof ResponsavelIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao-categorias': typeof GestaoCategoriasRoute
  '/gestao-noticias': typeof GestaoNoticiasRoute
  '/gestao-ouvidoria': typeof GestaoOuvidoriaRoute
  '/inadimplentes': typeof InadimplentesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/associado': typeof SiteAssociadoRoute
  '/contato': typeof SiteContatoRoute
  '/institucional': typeof SiteInstitucionalRoute
  '/noticias': typeof SiteNoticiasRoute
  '/ouvidoria': typeof SiteOuvidoriaRoute
  '/transparencia': typeof SiteTransparenciaRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/associado/painel': typeof AssociadoPainelRoute
  '/responsavel/dashboard': typeof ResponsavelDashboardRoute
  '/': typeof SiteIndexRoute
  '/alunos': typeof AlunosIndexRoute
  '/responsavel': typeof ResponsavelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/alunos': typeof AlunosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao-categorias': typeof GestaoCategoriasRoute
  '/gestao-noticias': typeof GestaoNoticiasRoute
  '/gestao-ouvidoria': typeof GestaoOuvidoriaRoute
  '/inadimplentes': typeof InadimplentesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/responsavel': typeof ResponsavelRouteWithChildren
  '/_site/associado': typeof SiteAssociadoRoute
  '/_site/contato': typeof SiteContatoRoute
  '/_site/institucional': typeof SiteInstitucionalRoute
  '/_site/noticias': typeof SiteNoticiasRoute
  '/_site/ouvidoria': typeof SiteOuvidoriaRoute
  '/_site/transparencia': typeof SiteTransparenciaRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/associado/painel': typeof AssociadoPainelRoute
  '/responsavel/dashboard': typeof ResponsavelDashboardRoute
  '/_site/': typeof SiteIndexRoute
  '/alunos/': typeof AlunosIndexRoute
  '/responsavel/': typeof ResponsavelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/dashboard'
    | '/financeiro'
    | '/gestao-categorias'
    | '/gestao-noticias'
    | '/gestao-ouvidoria'
    | '/inadimplentes'
    | '/login'
    | '/perfil'
    | '/relatorios'
    | '/responsavel'
    | '/associado'
    | '/contato'
    | '/institucional'
    | '/noticias'
    | '/ouvidoria'
    | '/transparencia'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/associado/painel'
    | '/responsavel/dashboard'
    | '/alunos/'
    | '/responsavel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/financeiro'
    | '/gestao-categorias'
    | '/gestao-noticias'
    | '/gestao-ouvidoria'
    | '/inadimplentes'
    | '/login'
    | '/perfil'
    | '/relatorios'
    | '/associado'
    | '/contato'
    | '/institucional'
    | '/noticias'
    | '/ouvidoria'
    | '/transparencia'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/associado/painel'
    | '/responsavel/dashboard'
    | '/'
    | '/alunos'
    | '/responsavel'
  id:
    | '__root__'
    | '/_site'
    | '/alunos'
    | '/dashboard'
    | '/financeiro'
    | '/gestao-categorias'
    | '/gestao-noticias'
    | '/gestao-ouvidoria'
    | '/inadimplentes'
    | '/login'
    | '/perfil'
    | '/relatorios'
    | '/responsavel'
    | '/_site/associado'
    | '/_site/contato'
    | '/_site/institucional'
    | '/_site/noticias'
    | '/_site/ouvidoria'
    | '/_site/transparencia'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/associado/painel'
    | '/responsavel/dashboard'
    | '/_site/'
    | '/alunos/'
    | '/responsavel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AlunosRoute: typeof AlunosRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FinanceiroRoute: typeof FinanceiroRoute
  GestaoCategoriasRoute: typeof GestaoCategoriasRoute
  GestaoNoticiasRoute: typeof GestaoNoticiasRoute
  GestaoOuvidoriaRoute: typeof GestaoOuvidoriaRoute
  InadimplentesRoute: typeof InadimplentesRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResponsavelRoute: typeof ResponsavelRouteWithChildren
  AssociadoPainelRoute: typeof AssociadoPainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/responsavel': {
      id: '/responsavel'
      path: '/responsavel'
      fullPath: '/responsavel'
      preLoaderRoute: typeof ResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inadimplentes': {
      id: '/inadimplentes'
      path: '/inadimplentes'
      fullPath: '/inadimplentes'
      preLoaderRoute: typeof InadimplentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-ouvidoria': {
      id: '/gestao-ouvidoria'
      path: '/gestao-ouvidoria'
      fullPath: '/gestao-ouvidoria'
      preLoaderRoute: typeof GestaoOuvidoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-noticias': {
      id: '/gestao-noticias'
      path: '/gestao-noticias'
      fullPath: '/gestao-noticias'
      preLoaderRoute: typeof GestaoNoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-categorias': {
      id: '/gestao-categorias'
      path: '/gestao-categorias'
      fullPath: '/gestao-categorias'
      preLoaderRoute: typeof GestaoCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsavel/': {
      id: '/responsavel/'
      path: '/'
      fullPath: '/responsavel/'
      preLoaderRoute: typeof ResponsavelIndexRouteImport
      parentRoute: typeof ResponsavelRoute
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/responsavel/dashboard': {
      id: '/responsavel/dashboard'
      path: '/dashboard'
      fullPath: '/responsavel/dashboard'
      preLoaderRoute: typeof ResponsavelDashboardRouteImport
      parentRoute: typeof ResponsavelRoute
    }
    '/associado/painel': {
      id: '/associado/painel'
      path: '/associado/painel'
      fullPath: '/associado/painel'
      preLoaderRoute: typeof AssociadoPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/novo': {
      id: '/alunos/novo'
      path: '/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AlunosNovoRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/alunos/$id': {
      id: '/alunos/$id'
      path: '/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AlunosIdRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/_site/transparencia': {
      id: '/_site/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof SiteTransparenciaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ouvidoria': {
      id: '/_site/ouvidoria'
      path: '/ouvidoria'
      fullPath: '/ouvidoria'
      preLoaderRoute: typeof SiteOuvidoriaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/noticias': {
      id: '/_site/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof SiteNoticiasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/institucional': {
      id: '/_site/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof SiteInstitucionalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/associado': {
      id: '/_site/associado'
      path: '/associado'
      fullPath: '/associado'
      preLoaderRoute: typeof SiteAssociadoRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAssociadoRoute: typeof SiteAssociadoRoute
  SiteContatoRoute: typeof SiteContatoRoute
  SiteInstitucionalRoute: typeof SiteInstitucionalRoute
  SiteNoticiasRoute: typeof SiteNoticiasRoute
  SiteOuvidoriaRoute: typeof SiteOuvidoriaRoute
  SiteTransparenciaRoute: typeof SiteTransparenciaRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAssociadoRoute: SiteAssociadoRoute,
  SiteContatoRoute: SiteContatoRoute,
  SiteInstitucionalRoute: SiteInstitucionalRoute,
  SiteNoticiasRoute: SiteNoticiasRoute,
  SiteOuvidoriaRoute: SiteOuvidoriaRoute,
  SiteTransparenciaRoute: SiteTransparenciaRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AlunosRouteChildren {
  AlunosIdRoute: typeof AlunosIdRoute
  AlunosNovoRoute: typeof AlunosNovoRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
}

const AlunosRouteChildren: AlunosRouteChildren = {
  AlunosIdRoute: AlunosIdRoute,
  AlunosNovoRoute: AlunosNovoRoute,
  AlunosIndexRoute: AlunosIndexRoute,
}

const AlunosRouteWithChildren =
  AlunosRoute._addFileChildren(AlunosRouteChildren)

interface ResponsavelRouteChildren {
  ResponsavelDashboardRoute: typeof ResponsavelDashboardRoute
  ResponsavelIndexRoute: typeof ResponsavelIndexRoute
}

const ResponsavelRouteChildren: ResponsavelRouteChildren = {
  ResponsavelDashboardRoute: ResponsavelDashboardRoute,
  ResponsavelIndexRoute: ResponsavelIndexRoute,
}

const ResponsavelRouteWithChildren = ResponsavelRoute._addFileChildren(
  ResponsavelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AlunosRoute: AlunosRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FinanceiroRoute: FinanceiroRoute,
  GestaoCategoriasRoute: GestaoCategoriasRoute,
  GestaoNoticiasRoute: GestaoNoticiasRoute,
  GestaoOuvidoriaRoute: GestaoOuvidoriaRoute,
  InadimplentesRoute: InadimplentesRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResponsavelRoute: ResponsavelRouteWithChildren,
  AssociadoPainelRoute: AssociadoPainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
